apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo
  namespace: default
spec:
  encryptedData:
    greeting: AgAC7DUQb1KAXhNgOL+X7DcNv+j7VXr7WUpZ6chycDbTIDHkhpwSHp/T6Zc4FleMA2QpadwNr21CqyflgoVoznPCThwS3YGi3G2iseMG5iBtlgO4r5Crvw1fX5eglY1bCBxTtkvkbHuECnD3t6KttJfzRYnbg2Hu0ggdZRSCmgSgn9UC2aAvjrB8q0zA8C8Dmjn6wD8wXUDxiY2biJPMdEpTh7kZ4bhCQZTMfU0iLjLIkt/JWgXX54Xjj+OgqDZKpEzvJb/BARJQvQL4aUlT/7Nx09WbS65FzkV7GFIVXeGwSc2H5JO/fkZlQwT+VPXHAqiljqb7GBkx2ThtFEdJ4/KUlXyHl18WwomVyx9d45vvKxPGBL/dXm6UjGH/e5XWeIJvK9PbqJM/93AKZYdIMftF8emGwqX4P/KanxrDBo6kz6mfVdSsyTuq333dEJGFIquAe+c3y8dOvcwY71WqkfjK45NcJEKMnHnd3Mw/s03q4DRddpeuvdNRclp84B9KdzTvBE5Q3tmWRRMc2/846wPasZ9kJ4h6DACMyiStk75zAGRmGgFvvCxf5BBoH8ZMeXHqE6HCz5sPi2b5gBb+BwhV2sHtYrIbXEA18Cfpq1AGiOkxmsLfsOGG0f7/QfjIozzaXzCWWjgd3wu+VDD8SVg8LlkPbn3A8iJ1e2ricRndzRdBWau6X1IzvA+Rg0kuPwknjynGYA==
  template:
    metadata:
      creationTimestamp: null
      name: demo
      namespace: default