---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-cloud-k8s-default-rolebinding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: spring-cloud-k8s-role
subjects:
  - kind: ServiceAccount
    name: default
